### ISSUE TITLE
network/create empty example value not working

### ISSUE THREAD

**Issue by jorgeboucas** [cytoscape/cyREST#53]
I am not managing to get a proper result even after playing with the example values.

**Comment by dotasek** [comment]
Here's my use case (I verified that this works moments ago):

1. Load an existing network.
2. Select some nodes and edges in that network.
3. Execute network/network_create with these parameters:
```
{
  "edgeList": "selected",
  "excludeEdges": "false",
  "networkName": "my_new_subnetwork.sif",
  "nodeList": "selected",
  "source": "current"
}
```

This should generate a new subnetwork.

Hopefully this helps. Since this issue relates to the command implementation, this issue will be handled by (http://code.cytoscape.org/redmine/issues/4116) and closed here.

**Comment by jorgeboucas** [comment]
with your example I got it nicely through.
